# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /fs03/share/users/romain.biassin/home/Documents/Image_rendu_ray/tp_ray_tracing

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /fs03/share/users/romain.biassin/home/Documents/Image_rendu_ray/tp_ray_tracing

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /fs03/share/users/romain.biassin/home/Documents/Image_rendu_ray/tp_ray_tracing/CMakeFiles /fs03/share/users/romain.biassin/home/Documents/Image_rendu_ray/tp_ray_tracing/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /fs03/share/users/romain.biassin/home/Documents/Image_rendu_ray/tp_ray_tracing/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pgm

# Build rule for target.
pgm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pgm
.PHONY : pgm

# fast build rule for target.
pgm/fast:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/build
.PHONY : pgm/fast

projet/src/image/color.o: projet/src/image/color.cpp.o
.PHONY : projet/src/image/color.o

# target to build an object file
projet/src/image/color.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/image/color.cpp.o
.PHONY : projet/src/image/color.cpp.o

projet/src/image/color.i: projet/src/image/color.cpp.i
.PHONY : projet/src/image/color.i

# target to preprocess a source file
projet/src/image/color.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/image/color.cpp.i
.PHONY : projet/src/image/color.cpp.i

projet/src/image/color.s: projet/src/image/color.cpp.s
.PHONY : projet/src/image/color.s

# target to generate assembly for a file
projet/src/image/color.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/image/color.cpp.s
.PHONY : projet/src/image/color.cpp.s

projet/src/image/image.o: projet/src/image/image.cpp.o
.PHONY : projet/src/image/image.o

# target to build an object file
projet/src/image/image.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/image/image.cpp.o
.PHONY : projet/src/image/image.cpp.o

projet/src/image/image.i: projet/src/image/image.cpp.i
.PHONY : projet/src/image/image.i

# target to preprocess a source file
projet/src/image/image.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/image/image.cpp.i
.PHONY : projet/src/image/image.cpp.i

projet/src/image/image.s: projet/src/image/image.cpp.s
.PHONY : projet/src/image/image.s

# target to generate assembly for a file
projet/src/image/image.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/image/image.cpp.s
.PHONY : projet/src/image/image.cpp.s

projet/src/image/image_zbuffer.o: projet/src/image/image_zbuffer.cpp.o
.PHONY : projet/src/image/image_zbuffer.o

# target to build an object file
projet/src/image/image_zbuffer.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/image/image_zbuffer.cpp.o
.PHONY : projet/src/image/image_zbuffer.cpp.o

projet/src/image/image_zbuffer.i: projet/src/image/image_zbuffer.cpp.i
.PHONY : projet/src/image/image_zbuffer.i

# target to preprocess a source file
projet/src/image/image_zbuffer.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/image/image_zbuffer.cpp.i
.PHONY : projet/src/image/image_zbuffer.cpp.i

projet/src/image/image_zbuffer.s: projet/src/image/image_zbuffer.cpp.s
.PHONY : projet/src/image/image_zbuffer.s

# target to generate assembly for a file
projet/src/image/image_zbuffer.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/image/image_zbuffer.cpp.s
.PHONY : projet/src/image/image_zbuffer.cpp.s

projet/src/image/io/image_ppm.o: projet/src/image/io/image_ppm.cpp.o
.PHONY : projet/src/image/io/image_ppm.o

# target to build an object file
projet/src/image/io/image_ppm.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/image/io/image_ppm.cpp.o
.PHONY : projet/src/image/io/image_ppm.cpp.o

projet/src/image/io/image_ppm.i: projet/src/image/io/image_ppm.cpp.i
.PHONY : projet/src/image/io/image_ppm.i

# target to preprocess a source file
projet/src/image/io/image_ppm.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/image/io/image_ppm.cpp.i
.PHONY : projet/src/image/io/image_ppm.cpp.i

projet/src/image/io/image_ppm.s: projet/src/image/io/image_ppm.cpp.s
.PHONY : projet/src/image/io/image_ppm.s

# target to generate assembly for a file
projet/src/image/io/image_ppm.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/image/io/image_ppm.cpp.s
.PHONY : projet/src/image/io/image_ppm.cpp.s

projet/src/image/ivec2.o: projet/src/image/ivec2.cpp.o
.PHONY : projet/src/image/ivec2.o

# target to build an object file
projet/src/image/ivec2.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/image/ivec2.cpp.o
.PHONY : projet/src/image/ivec2.cpp.o

projet/src/image/ivec2.i: projet/src/image/ivec2.cpp.i
.PHONY : projet/src/image/ivec2.i

# target to preprocess a source file
projet/src/image/ivec2.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/image/ivec2.cpp.i
.PHONY : projet/src/image/ivec2.cpp.i

projet/src/image/ivec2.s: projet/src/image/ivec2.cpp.s
.PHONY : projet/src/image/ivec2.s

# target to generate assembly for a file
projet/src/image/ivec2.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/image/ivec2.cpp.s
.PHONY : projet/src/image/ivec2.cpp.s

projet/src/image/texture.o: projet/src/image/texture.cpp.o
.PHONY : projet/src/image/texture.o

# target to build an object file
projet/src/image/texture.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/image/texture.cpp.o
.PHONY : projet/src/image/texture.cpp.o

projet/src/image/texture.i: projet/src/image/texture.cpp.i
.PHONY : projet/src/image/texture.i

# target to preprocess a source file
projet/src/image/texture.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/image/texture.cpp.i
.PHONY : projet/src/image/texture.cpp.i

projet/src/image/texture.s: projet/src/image/texture.cpp.s
.PHONY : projet/src/image/texture.s

# target to generate assembly for a file
projet/src/image/texture.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/image/texture.cpp.s
.PHONY : projet/src/image/texture.cpp.s

projet/src/lib/3d/mat1x4.o: projet/src/lib/3d/mat1x4.cpp.o
.PHONY : projet/src/lib/3d/mat1x4.o

# target to build an object file
projet/src/lib/3d/mat1x4.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/3d/mat1x4.cpp.o
.PHONY : projet/src/lib/3d/mat1x4.cpp.o

projet/src/lib/3d/mat1x4.i: projet/src/lib/3d/mat1x4.cpp.i
.PHONY : projet/src/lib/3d/mat1x4.i

# target to preprocess a source file
projet/src/lib/3d/mat1x4.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/3d/mat1x4.cpp.i
.PHONY : projet/src/lib/3d/mat1x4.cpp.i

projet/src/lib/3d/mat1x4.s: projet/src/lib/3d/mat1x4.cpp.s
.PHONY : projet/src/lib/3d/mat1x4.s

# target to generate assembly for a file
projet/src/lib/3d/mat1x4.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/3d/mat1x4.cpp.s
.PHONY : projet/src/lib/3d/mat1x4.cpp.s

projet/src/lib/3d/mat2.o: projet/src/lib/3d/mat2.cpp.o
.PHONY : projet/src/lib/3d/mat2.o

# target to build an object file
projet/src/lib/3d/mat2.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/3d/mat2.cpp.o
.PHONY : projet/src/lib/3d/mat2.cpp.o

projet/src/lib/3d/mat2.i: projet/src/lib/3d/mat2.cpp.i
.PHONY : projet/src/lib/3d/mat2.i

# target to preprocess a source file
projet/src/lib/3d/mat2.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/3d/mat2.cpp.i
.PHONY : projet/src/lib/3d/mat2.cpp.i

projet/src/lib/3d/mat2.s: projet/src/lib/3d/mat2.cpp.s
.PHONY : projet/src/lib/3d/mat2.s

# target to generate assembly for a file
projet/src/lib/3d/mat2.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/3d/mat2.cpp.s
.PHONY : projet/src/lib/3d/mat2.cpp.s

projet/src/lib/3d/mat3.o: projet/src/lib/3d/mat3.cpp.o
.PHONY : projet/src/lib/3d/mat3.o

# target to build an object file
projet/src/lib/3d/mat3.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/3d/mat3.cpp.o
.PHONY : projet/src/lib/3d/mat3.cpp.o

projet/src/lib/3d/mat3.i: projet/src/lib/3d/mat3.cpp.i
.PHONY : projet/src/lib/3d/mat3.i

# target to preprocess a source file
projet/src/lib/3d/mat3.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/3d/mat3.cpp.i
.PHONY : projet/src/lib/3d/mat3.cpp.i

projet/src/lib/3d/mat3.s: projet/src/lib/3d/mat3.cpp.s
.PHONY : projet/src/lib/3d/mat3.s

# target to generate assembly for a file
projet/src/lib/3d/mat3.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/3d/mat3.cpp.s
.PHONY : projet/src/lib/3d/mat3.cpp.s

projet/src/lib/3d/mat4.o: projet/src/lib/3d/mat4.cpp.o
.PHONY : projet/src/lib/3d/mat4.o

# target to build an object file
projet/src/lib/3d/mat4.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/3d/mat4.cpp.o
.PHONY : projet/src/lib/3d/mat4.cpp.o

projet/src/lib/3d/mat4.i: projet/src/lib/3d/mat4.cpp.i
.PHONY : projet/src/lib/3d/mat4.i

# target to preprocess a source file
projet/src/lib/3d/mat4.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/3d/mat4.cpp.i
.PHONY : projet/src/lib/3d/mat4.cpp.i

projet/src/lib/3d/mat4.s: projet/src/lib/3d/mat4.cpp.s
.PHONY : projet/src/lib/3d/mat4.s

# target to generate assembly for a file
projet/src/lib/3d/mat4.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/3d/mat4.cpp.s
.PHONY : projet/src/lib/3d/mat4.cpp.s

projet/src/lib/3d/mat4x1.o: projet/src/lib/3d/mat4x1.cpp.o
.PHONY : projet/src/lib/3d/mat4x1.o

# target to build an object file
projet/src/lib/3d/mat4x1.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/3d/mat4x1.cpp.o
.PHONY : projet/src/lib/3d/mat4x1.cpp.o

projet/src/lib/3d/mat4x1.i: projet/src/lib/3d/mat4x1.cpp.i
.PHONY : projet/src/lib/3d/mat4x1.i

# target to preprocess a source file
projet/src/lib/3d/mat4x1.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/3d/mat4x1.cpp.i
.PHONY : projet/src/lib/3d/mat4x1.cpp.i

projet/src/lib/3d/mat4x1.s: projet/src/lib/3d/mat4x1.cpp.s
.PHONY : projet/src/lib/3d/mat4x1.s

# target to generate assembly for a file
projet/src/lib/3d/mat4x1.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/3d/mat4x1.cpp.s
.PHONY : projet/src/lib/3d/mat4x1.cpp.s

projet/src/lib/3d/quaternion.o: projet/src/lib/3d/quaternion.cpp.o
.PHONY : projet/src/lib/3d/quaternion.o

# target to build an object file
projet/src/lib/3d/quaternion.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/3d/quaternion.cpp.o
.PHONY : projet/src/lib/3d/quaternion.cpp.o

projet/src/lib/3d/quaternion.i: projet/src/lib/3d/quaternion.cpp.i
.PHONY : projet/src/lib/3d/quaternion.i

# target to preprocess a source file
projet/src/lib/3d/quaternion.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/3d/quaternion.cpp.i
.PHONY : projet/src/lib/3d/quaternion.cpp.i

projet/src/lib/3d/quaternion.s: projet/src/lib/3d/quaternion.cpp.s
.PHONY : projet/src/lib/3d/quaternion.s

# target to generate assembly for a file
projet/src/lib/3d/quaternion.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/3d/quaternion.cpp.s
.PHONY : projet/src/lib/3d/quaternion.cpp.s

projet/src/lib/3d/vec2.o: projet/src/lib/3d/vec2.cpp.o
.PHONY : projet/src/lib/3d/vec2.o

# target to build an object file
projet/src/lib/3d/vec2.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/3d/vec2.cpp.o
.PHONY : projet/src/lib/3d/vec2.cpp.o

projet/src/lib/3d/vec2.i: projet/src/lib/3d/vec2.cpp.i
.PHONY : projet/src/lib/3d/vec2.i

# target to preprocess a source file
projet/src/lib/3d/vec2.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/3d/vec2.cpp.i
.PHONY : projet/src/lib/3d/vec2.cpp.i

projet/src/lib/3d/vec2.s: projet/src/lib/3d/vec2.cpp.s
.PHONY : projet/src/lib/3d/vec2.s

# target to generate assembly for a file
projet/src/lib/3d/vec2.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/3d/vec2.cpp.s
.PHONY : projet/src/lib/3d/vec2.cpp.s

projet/src/lib/3d/vec3.o: projet/src/lib/3d/vec3.cpp.o
.PHONY : projet/src/lib/3d/vec3.o

# target to build an object file
projet/src/lib/3d/vec3.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/3d/vec3.cpp.o
.PHONY : projet/src/lib/3d/vec3.cpp.o

projet/src/lib/3d/vec3.i: projet/src/lib/3d/vec3.cpp.i
.PHONY : projet/src/lib/3d/vec3.i

# target to preprocess a source file
projet/src/lib/3d/vec3.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/3d/vec3.cpp.i
.PHONY : projet/src/lib/3d/vec3.cpp.i

projet/src/lib/3d/vec3.s: projet/src/lib/3d/vec3.cpp.s
.PHONY : projet/src/lib/3d/vec3.s

# target to generate assembly for a file
projet/src/lib/3d/vec3.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/3d/vec3.cpp.s
.PHONY : projet/src/lib/3d/vec3.cpp.s

projet/src/lib/3d/vec4.o: projet/src/lib/3d/vec4.cpp.o
.PHONY : projet/src/lib/3d/vec4.o

# target to build an object file
projet/src/lib/3d/vec4.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/3d/vec4.cpp.o
.PHONY : projet/src/lib/3d/vec4.cpp.o

projet/src/lib/3d/vec4.i: projet/src/lib/3d/vec4.cpp.i
.PHONY : projet/src/lib/3d/vec4.i

# target to preprocess a source file
projet/src/lib/3d/vec4.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/3d/vec4.cpp.i
.PHONY : projet/src/lib/3d/vec4.cpp.i

projet/src/lib/3d/vec4.s: projet/src/lib/3d/vec4.cpp.s
.PHONY : projet/src/lib/3d/vec4.s

# target to generate assembly for a file
projet/src/lib/3d/vec4.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/3d/vec4.cpp.s
.PHONY : projet/src/lib/3d/vec4.cpp.s

projet/src/lib/common/backtrace.o: projet/src/lib/common/backtrace.cpp.o
.PHONY : projet/src/lib/common/backtrace.o

# target to build an object file
projet/src/lib/common/backtrace.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/common/backtrace.cpp.o
.PHONY : projet/src/lib/common/backtrace.cpp.o

projet/src/lib/common/backtrace.i: projet/src/lib/common/backtrace.cpp.i
.PHONY : projet/src/lib/common/backtrace.i

# target to preprocess a source file
projet/src/lib/common/backtrace.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/common/backtrace.cpp.i
.PHONY : projet/src/lib/common/backtrace.cpp.i

projet/src/lib/common/backtrace.s: projet/src/lib/common/backtrace.cpp.s
.PHONY : projet/src/lib/common/backtrace.s

# target to generate assembly for a file
projet/src/lib/common/backtrace.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/common/backtrace.cpp.s
.PHONY : projet/src/lib/common/backtrace.cpp.s

projet/src/lib/common/basic_functions.o: projet/src/lib/common/basic_functions.cpp.o
.PHONY : projet/src/lib/common/basic_functions.o

# target to build an object file
projet/src/lib/common/basic_functions.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/common/basic_functions.cpp.o
.PHONY : projet/src/lib/common/basic_functions.cpp.o

projet/src/lib/common/basic_functions.i: projet/src/lib/common/basic_functions.cpp.i
.PHONY : projet/src/lib/common/basic_functions.i

# target to preprocess a source file
projet/src/lib/common/basic_functions.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/common/basic_functions.cpp.i
.PHONY : projet/src/lib/common/basic_functions.cpp.i

projet/src/lib/common/basic_functions.s: projet/src/lib/common/basic_functions.cpp.s
.PHONY : projet/src/lib/common/basic_functions.s

# target to generate assembly for a file
projet/src/lib/common/basic_functions.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/common/basic_functions.cpp.s
.PHONY : projet/src/lib/common/basic_functions.cpp.s

projet/src/lib/common/exception_cpe.o: projet/src/lib/common/exception_cpe.cpp.o
.PHONY : projet/src/lib/common/exception_cpe.o

# target to build an object file
projet/src/lib/common/exception_cpe.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/common/exception_cpe.cpp.o
.PHONY : projet/src/lib/common/exception_cpe.cpp.o

projet/src/lib/common/exception_cpe.i: projet/src/lib/common/exception_cpe.cpp.i
.PHONY : projet/src/lib/common/exception_cpe.i

# target to preprocess a source file
projet/src/lib/common/exception_cpe.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/common/exception_cpe.cpp.i
.PHONY : projet/src/lib/common/exception_cpe.cpp.i

projet/src/lib/common/exception_cpe.s: projet/src/lib/common/exception_cpe.cpp.s
.PHONY : projet/src/lib/common/exception_cpe.s

# target to generate assembly for a file
projet/src/lib/common/exception_cpe.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/common/exception_cpe.cpp.s
.PHONY : projet/src/lib/common/exception_cpe.cpp.s

projet/src/lib/mesh/format/mesh_io_obj.o: projet/src/lib/mesh/format/mesh_io_obj.cpp.o
.PHONY : projet/src/lib/mesh/format/mesh_io_obj.o

# target to build an object file
projet/src/lib/mesh/format/mesh_io_obj.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/mesh/format/mesh_io_obj.cpp.o
.PHONY : projet/src/lib/mesh/format/mesh_io_obj.cpp.o

projet/src/lib/mesh/format/mesh_io_obj.i: projet/src/lib/mesh/format/mesh_io_obj.cpp.i
.PHONY : projet/src/lib/mesh/format/mesh_io_obj.i

# target to preprocess a source file
projet/src/lib/mesh/format/mesh_io_obj.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/mesh/format/mesh_io_obj.cpp.i
.PHONY : projet/src/lib/mesh/format/mesh_io_obj.cpp.i

projet/src/lib/mesh/format/mesh_io_obj.s: projet/src/lib/mesh/format/mesh_io_obj.cpp.s
.PHONY : projet/src/lib/mesh/format/mesh_io_obj.s

# target to generate assembly for a file
projet/src/lib/mesh/format/mesh_io_obj.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/mesh/format/mesh_io_obj.cpp.s
.PHONY : projet/src/lib/mesh/format/mesh_io_obj.cpp.s

projet/src/lib/mesh/format/mesh_io_off.o: projet/src/lib/mesh/format/mesh_io_off.cpp.o
.PHONY : projet/src/lib/mesh/format/mesh_io_off.o

# target to build an object file
projet/src/lib/mesh/format/mesh_io_off.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/mesh/format/mesh_io_off.cpp.o
.PHONY : projet/src/lib/mesh/format/mesh_io_off.cpp.o

projet/src/lib/mesh/format/mesh_io_off.i: projet/src/lib/mesh/format/mesh_io_off.cpp.i
.PHONY : projet/src/lib/mesh/format/mesh_io_off.i

# target to preprocess a source file
projet/src/lib/mesh/format/mesh_io_off.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/mesh/format/mesh_io_off.cpp.i
.PHONY : projet/src/lib/mesh/format/mesh_io_off.cpp.i

projet/src/lib/mesh/format/mesh_io_off.s: projet/src/lib/mesh/format/mesh_io_off.cpp.s
.PHONY : projet/src/lib/mesh/format/mesh_io_off.s

# target to generate assembly for a file
projet/src/lib/mesh/format/mesh_io_off.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/mesh/format/mesh_io_off.cpp.s
.PHONY : projet/src/lib/mesh/format/mesh_io_off.cpp.s

projet/src/lib/mesh/mesh.o: projet/src/lib/mesh/mesh.cpp.o
.PHONY : projet/src/lib/mesh/mesh.o

# target to build an object file
projet/src/lib/mesh/mesh.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/mesh/mesh.cpp.o
.PHONY : projet/src/lib/mesh/mesh.cpp.o

projet/src/lib/mesh/mesh.i: projet/src/lib/mesh/mesh.cpp.i
.PHONY : projet/src/lib/mesh/mesh.i

# target to preprocess a source file
projet/src/lib/mesh/mesh.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/mesh/mesh.cpp.i
.PHONY : projet/src/lib/mesh/mesh.cpp.i

projet/src/lib/mesh/mesh.s: projet/src/lib/mesh/mesh.cpp.s
.PHONY : projet/src/lib/mesh/mesh.s

# target to generate assembly for a file
projet/src/lib/mesh/mesh.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/mesh/mesh.cpp.s
.PHONY : projet/src/lib/mesh/mesh.cpp.s

projet/src/lib/mesh/mesh_basic.o: projet/src/lib/mesh/mesh_basic.cpp.o
.PHONY : projet/src/lib/mesh/mesh_basic.o

# target to build an object file
projet/src/lib/mesh/mesh_basic.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/mesh/mesh_basic.cpp.o
.PHONY : projet/src/lib/mesh/mesh_basic.cpp.o

projet/src/lib/mesh/mesh_basic.i: projet/src/lib/mesh/mesh_basic.cpp.i
.PHONY : projet/src/lib/mesh/mesh_basic.i

# target to preprocess a source file
projet/src/lib/mesh/mesh_basic.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/mesh/mesh_basic.cpp.i
.PHONY : projet/src/lib/mesh/mesh_basic.cpp.i

projet/src/lib/mesh/mesh_basic.s: projet/src/lib/mesh/mesh_basic.cpp.s
.PHONY : projet/src/lib/mesh/mesh_basic.s

# target to generate assembly for a file
projet/src/lib/mesh/mesh_basic.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/mesh/mesh_basic.cpp.s
.PHONY : projet/src/lib/mesh/mesh_basic.cpp.s

projet/src/lib/mesh/mesh_io.o: projet/src/lib/mesh/mesh_io.cpp.o
.PHONY : projet/src/lib/mesh/mesh_io.o

# target to build an object file
projet/src/lib/mesh/mesh_io.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/mesh/mesh_io.cpp.o
.PHONY : projet/src/lib/mesh/mesh_io.cpp.o

projet/src/lib/mesh/mesh_io.i: projet/src/lib/mesh/mesh_io.cpp.i
.PHONY : projet/src/lib/mesh/mesh_io.i

# target to preprocess a source file
projet/src/lib/mesh/mesh_io.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/mesh/mesh_io.cpp.i
.PHONY : projet/src/lib/mesh/mesh_io.cpp.i

projet/src/lib/mesh/mesh_io.s: projet/src/lib/mesh/mesh_io.cpp.s
.PHONY : projet/src/lib/mesh/mesh_io.s

# target to generate assembly for a file
projet/src/lib/mesh/mesh_io.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/mesh/mesh_io.cpp.s
.PHONY : projet/src/lib/mesh/mesh_io.cpp.s

projet/src/lib/mesh/mesh_parametric.o: projet/src/lib/mesh/mesh_parametric.cpp.o
.PHONY : projet/src/lib/mesh/mesh_parametric.o

# target to build an object file
projet/src/lib/mesh/mesh_parametric.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/mesh/mesh_parametric.cpp.o
.PHONY : projet/src/lib/mesh/mesh_parametric.cpp.o

projet/src/lib/mesh/mesh_parametric.i: projet/src/lib/mesh/mesh_parametric.cpp.i
.PHONY : projet/src/lib/mesh/mesh_parametric.i

# target to preprocess a source file
projet/src/lib/mesh/mesh_parametric.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/mesh/mesh_parametric.cpp.i
.PHONY : projet/src/lib/mesh/mesh_parametric.cpp.i

projet/src/lib/mesh/mesh_parametric.s: projet/src/lib/mesh/mesh_parametric.cpp.s
.PHONY : projet/src/lib/mesh/mesh_parametric.s

# target to generate assembly for a file
projet/src/lib/mesh/mesh_parametric.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/mesh/mesh_parametric.cpp.s
.PHONY : projet/src/lib/mesh/mesh_parametric.cpp.s

projet/src/lib/mesh/triangle_index.o: projet/src/lib/mesh/triangle_index.cpp.o
.PHONY : projet/src/lib/mesh/triangle_index.o

# target to build an object file
projet/src/lib/mesh/triangle_index.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/mesh/triangle_index.cpp.o
.PHONY : projet/src/lib/mesh/triangle_index.cpp.o

projet/src/lib/mesh/triangle_index.i: projet/src/lib/mesh/triangle_index.cpp.i
.PHONY : projet/src/lib/mesh/triangle_index.i

# target to preprocess a source file
projet/src/lib/mesh/triangle_index.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/mesh/triangle_index.cpp.i
.PHONY : projet/src/lib/mesh/triangle_index.cpp.i

projet/src/lib/mesh/triangle_index.s: projet/src/lib/mesh/triangle_index.cpp.s
.PHONY : projet/src/lib/mesh/triangle_index.s

# target to generate assembly for a file
projet/src/lib/mesh/triangle_index.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/lib/mesh/triangle_index.cpp.s
.PHONY : projet/src/lib/mesh/triangle_index.cpp.s

projet/src/local/main.o: projet/src/local/main.cpp.o
.PHONY : projet/src/local/main.o

# target to build an object file
projet/src/local/main.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/local/main.cpp.o
.PHONY : projet/src/local/main.cpp.o

projet/src/local/main.i: projet/src/local/main.cpp.i
.PHONY : projet/src/local/main.i

# target to preprocess a source file
projet/src/local/main.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/local/main.cpp.i
.PHONY : projet/src/local/main.cpp.i

projet/src/local/main.s: projet/src/local/main.cpp.s
.PHONY : projet/src/local/main.s

# target to generate assembly for a file
projet/src/local/main.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/local/main.cpp.s
.PHONY : projet/src/local/main.cpp.s

projet/src/ray_tracing/primitives/intersection_data.o: projet/src/ray_tracing/primitives/intersection_data.cpp.o
.PHONY : projet/src/ray_tracing/primitives/intersection_data.o

# target to build an object file
projet/src/ray_tracing/primitives/intersection_data.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/ray_tracing/primitives/intersection_data.cpp.o
.PHONY : projet/src/ray_tracing/primitives/intersection_data.cpp.o

projet/src/ray_tracing/primitives/intersection_data.i: projet/src/ray_tracing/primitives/intersection_data.cpp.i
.PHONY : projet/src/ray_tracing/primitives/intersection_data.i

# target to preprocess a source file
projet/src/ray_tracing/primitives/intersection_data.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/ray_tracing/primitives/intersection_data.cpp.i
.PHONY : projet/src/ray_tracing/primitives/intersection_data.cpp.i

projet/src/ray_tracing/primitives/intersection_data.s: projet/src/ray_tracing/primitives/intersection_data.cpp.s
.PHONY : projet/src/ray_tracing/primitives/intersection_data.s

# target to generate assembly for a file
projet/src/ray_tracing/primitives/intersection_data.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/ray_tracing/primitives/intersection_data.cpp.s
.PHONY : projet/src/ray_tracing/primitives/intersection_data.cpp.s

projet/src/ray_tracing/primitives/plane.o: projet/src/ray_tracing/primitives/plane.cpp.o
.PHONY : projet/src/ray_tracing/primitives/plane.o

# target to build an object file
projet/src/ray_tracing/primitives/plane.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/ray_tracing/primitives/plane.cpp.o
.PHONY : projet/src/ray_tracing/primitives/plane.cpp.o

projet/src/ray_tracing/primitives/plane.i: projet/src/ray_tracing/primitives/plane.cpp.i
.PHONY : projet/src/ray_tracing/primitives/plane.i

# target to preprocess a source file
projet/src/ray_tracing/primitives/plane.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/ray_tracing/primitives/plane.cpp.i
.PHONY : projet/src/ray_tracing/primitives/plane.cpp.i

projet/src/ray_tracing/primitives/plane.s: projet/src/ray_tracing/primitives/plane.cpp.s
.PHONY : projet/src/ray_tracing/primitives/plane.s

# target to generate assembly for a file
projet/src/ray_tracing/primitives/plane.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/ray_tracing/primitives/plane.cpp.s
.PHONY : projet/src/ray_tracing/primitives/plane.cpp.s

projet/src/ray_tracing/primitives/primitive_basic.o: projet/src/ray_tracing/primitives/primitive_basic.cpp.o
.PHONY : projet/src/ray_tracing/primitives/primitive_basic.o

# target to build an object file
projet/src/ray_tracing/primitives/primitive_basic.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/ray_tracing/primitives/primitive_basic.cpp.o
.PHONY : projet/src/ray_tracing/primitives/primitive_basic.cpp.o

projet/src/ray_tracing/primitives/primitive_basic.i: projet/src/ray_tracing/primitives/primitive_basic.cpp.i
.PHONY : projet/src/ray_tracing/primitives/primitive_basic.i

# target to preprocess a source file
projet/src/ray_tracing/primitives/primitive_basic.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/ray_tracing/primitives/primitive_basic.cpp.i
.PHONY : projet/src/ray_tracing/primitives/primitive_basic.cpp.i

projet/src/ray_tracing/primitives/primitive_basic.s: projet/src/ray_tracing/primitives/primitive_basic.cpp.s
.PHONY : projet/src/ray_tracing/primitives/primitive_basic.s

# target to generate assembly for a file
projet/src/ray_tracing/primitives/primitive_basic.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/ray_tracing/primitives/primitive_basic.cpp.s
.PHONY : projet/src/ray_tracing/primitives/primitive_basic.cpp.s

projet/src/ray_tracing/primitives/sphere.o: projet/src/ray_tracing/primitives/sphere.cpp.o
.PHONY : projet/src/ray_tracing/primitives/sphere.o

# target to build an object file
projet/src/ray_tracing/primitives/sphere.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/ray_tracing/primitives/sphere.cpp.o
.PHONY : projet/src/ray_tracing/primitives/sphere.cpp.o

projet/src/ray_tracing/primitives/sphere.i: projet/src/ray_tracing/primitives/sphere.cpp.i
.PHONY : projet/src/ray_tracing/primitives/sphere.i

# target to preprocess a source file
projet/src/ray_tracing/primitives/sphere.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/ray_tracing/primitives/sphere.cpp.i
.PHONY : projet/src/ray_tracing/primitives/sphere.cpp.i

projet/src/ray_tracing/primitives/sphere.s: projet/src/ray_tracing/primitives/sphere.cpp.s
.PHONY : projet/src/ray_tracing/primitives/sphere.s

# target to generate assembly for a file
projet/src/ray_tracing/primitives/sphere.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/ray_tracing/primitives/sphere.cpp.s
.PHONY : projet/src/ray_tracing/primitives/sphere.cpp.s

projet/src/ray_tracing/render_engine/render_engine.o: projet/src/ray_tracing/render_engine/render_engine.cpp.o
.PHONY : projet/src/ray_tracing/render_engine/render_engine.o

# target to build an object file
projet/src/ray_tracing/render_engine/render_engine.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/ray_tracing/render_engine/render_engine.cpp.o
.PHONY : projet/src/ray_tracing/render_engine/render_engine.cpp.o

projet/src/ray_tracing/render_engine/render_engine.i: projet/src/ray_tracing/render_engine/render_engine.cpp.i
.PHONY : projet/src/ray_tracing/render_engine/render_engine.i

# target to preprocess a source file
projet/src/ray_tracing/render_engine/render_engine.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/ray_tracing/render_engine/render_engine.cpp.i
.PHONY : projet/src/ray_tracing/render_engine/render_engine.cpp.i

projet/src/ray_tracing/render_engine/render_engine.s: projet/src/ray_tracing/render_engine/render_engine.cpp.s
.PHONY : projet/src/ray_tracing/render_engine/render_engine.s

# target to generate assembly for a file
projet/src/ray_tracing/render_engine/render_engine.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/ray_tracing/render_engine/render_engine.cpp.s
.PHONY : projet/src/ray_tracing/render_engine/render_engine.cpp.s

projet/src/ray_tracing/scene/anti_aliasing_table.o: projet/src/ray_tracing/scene/anti_aliasing_table.cpp.o
.PHONY : projet/src/ray_tracing/scene/anti_aliasing_table.o

# target to build an object file
projet/src/ray_tracing/scene/anti_aliasing_table.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/ray_tracing/scene/anti_aliasing_table.cpp.o
.PHONY : projet/src/ray_tracing/scene/anti_aliasing_table.cpp.o

projet/src/ray_tracing/scene/anti_aliasing_table.i: projet/src/ray_tracing/scene/anti_aliasing_table.cpp.i
.PHONY : projet/src/ray_tracing/scene/anti_aliasing_table.i

# target to preprocess a source file
projet/src/ray_tracing/scene/anti_aliasing_table.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/ray_tracing/scene/anti_aliasing_table.cpp.i
.PHONY : projet/src/ray_tracing/scene/anti_aliasing_table.cpp.i

projet/src/ray_tracing/scene/anti_aliasing_table.s: projet/src/ray_tracing/scene/anti_aliasing_table.cpp.s
.PHONY : projet/src/ray_tracing/scene/anti_aliasing_table.s

# target to generate assembly for a file
projet/src/ray_tracing/scene/anti_aliasing_table.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/ray_tracing/scene/anti_aliasing_table.cpp.s
.PHONY : projet/src/ray_tracing/scene/anti_aliasing_table.cpp.s

projet/src/ray_tracing/scene/camera.o: projet/src/ray_tracing/scene/camera.cpp.o
.PHONY : projet/src/ray_tracing/scene/camera.o

# target to build an object file
projet/src/ray_tracing/scene/camera.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/ray_tracing/scene/camera.cpp.o
.PHONY : projet/src/ray_tracing/scene/camera.cpp.o

projet/src/ray_tracing/scene/camera.i: projet/src/ray_tracing/scene/camera.cpp.i
.PHONY : projet/src/ray_tracing/scene/camera.i

# target to preprocess a source file
projet/src/ray_tracing/scene/camera.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/ray_tracing/scene/camera.cpp.i
.PHONY : projet/src/ray_tracing/scene/camera.cpp.i

projet/src/ray_tracing/scene/camera.s: projet/src/ray_tracing/scene/camera.cpp.s
.PHONY : projet/src/ray_tracing/scene/camera.s

# target to generate assembly for a file
projet/src/ray_tracing/scene/camera.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/ray_tracing/scene/camera.cpp.s
.PHONY : projet/src/ray_tracing/scene/camera.cpp.s

projet/src/ray_tracing/scene/light.o: projet/src/ray_tracing/scene/light.cpp.o
.PHONY : projet/src/ray_tracing/scene/light.o

# target to build an object file
projet/src/ray_tracing/scene/light.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/ray_tracing/scene/light.cpp.o
.PHONY : projet/src/ray_tracing/scene/light.cpp.o

projet/src/ray_tracing/scene/light.i: projet/src/ray_tracing/scene/light.cpp.i
.PHONY : projet/src/ray_tracing/scene/light.i

# target to preprocess a source file
projet/src/ray_tracing/scene/light.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/ray_tracing/scene/light.cpp.i
.PHONY : projet/src/ray_tracing/scene/light.cpp.i

projet/src/ray_tracing/scene/light.s: projet/src/ray_tracing/scene/light.cpp.s
.PHONY : projet/src/ray_tracing/scene/light.s

# target to generate assembly for a file
projet/src/ray_tracing/scene/light.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/ray_tracing/scene/light.cpp.s
.PHONY : projet/src/ray_tracing/scene/light.cpp.s

projet/src/ray_tracing/scene/material.o: projet/src/ray_tracing/scene/material.cpp.o
.PHONY : projet/src/ray_tracing/scene/material.o

# target to build an object file
projet/src/ray_tracing/scene/material.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/ray_tracing/scene/material.cpp.o
.PHONY : projet/src/ray_tracing/scene/material.cpp.o

projet/src/ray_tracing/scene/material.i: projet/src/ray_tracing/scene/material.cpp.i
.PHONY : projet/src/ray_tracing/scene/material.i

# target to preprocess a source file
projet/src/ray_tracing/scene/material.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/ray_tracing/scene/material.cpp.i
.PHONY : projet/src/ray_tracing/scene/material.cpp.i

projet/src/ray_tracing/scene/material.s: projet/src/ray_tracing/scene/material.cpp.s
.PHONY : projet/src/ray_tracing/scene/material.s

# target to generate assembly for a file
projet/src/ray_tracing/scene/material.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/ray_tracing/scene/material.cpp.s
.PHONY : projet/src/ray_tracing/scene/material.cpp.s

projet/src/ray_tracing/scene/ray.o: projet/src/ray_tracing/scene/ray.cpp.o
.PHONY : projet/src/ray_tracing/scene/ray.o

# target to build an object file
projet/src/ray_tracing/scene/ray.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/ray_tracing/scene/ray.cpp.o
.PHONY : projet/src/ray_tracing/scene/ray.cpp.o

projet/src/ray_tracing/scene/ray.i: projet/src/ray_tracing/scene/ray.cpp.i
.PHONY : projet/src/ray_tracing/scene/ray.i

# target to preprocess a source file
projet/src/ray_tracing/scene/ray.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/ray_tracing/scene/ray.cpp.i
.PHONY : projet/src/ray_tracing/scene/ray.cpp.i

projet/src/ray_tracing/scene/ray.s: projet/src/ray_tracing/scene/ray.cpp.s
.PHONY : projet/src/ray_tracing/scene/ray.s

# target to generate assembly for a file
projet/src/ray_tracing/scene/ray.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/ray_tracing/scene/ray.cpp.s
.PHONY : projet/src/ray_tracing/scene/ray.cpp.s

projet/src/ray_tracing/scene/scene_parameter.o: projet/src/ray_tracing/scene/scene_parameter.cpp.o
.PHONY : projet/src/ray_tracing/scene/scene_parameter.o

# target to build an object file
projet/src/ray_tracing/scene/scene_parameter.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/ray_tracing/scene/scene_parameter.cpp.o
.PHONY : projet/src/ray_tracing/scene/scene_parameter.cpp.o

projet/src/ray_tracing/scene/scene_parameter.i: projet/src/ray_tracing/scene/scene_parameter.cpp.i
.PHONY : projet/src/ray_tracing/scene/scene_parameter.i

# target to preprocess a source file
projet/src/ray_tracing/scene/scene_parameter.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/ray_tracing/scene/scene_parameter.cpp.i
.PHONY : projet/src/ray_tracing/scene/scene_parameter.cpp.i

projet/src/ray_tracing/scene/scene_parameter.s: projet/src/ray_tracing/scene/scene_parameter.cpp.s
.PHONY : projet/src/ray_tracing/scene/scene_parameter.s

# target to generate assembly for a file
projet/src/ray_tracing/scene/scene_parameter.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/ray_tracing/scene/scene_parameter.cpp.s
.PHONY : projet/src/ray_tracing/scene/scene_parameter.cpp.s

projet/src/ray_tracing/scene/shading_parameter.o: projet/src/ray_tracing/scene/shading_parameter.cpp.o
.PHONY : projet/src/ray_tracing/scene/shading_parameter.o

# target to build an object file
projet/src/ray_tracing/scene/shading_parameter.cpp.o:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/ray_tracing/scene/shading_parameter.cpp.o
.PHONY : projet/src/ray_tracing/scene/shading_parameter.cpp.o

projet/src/ray_tracing/scene/shading_parameter.i: projet/src/ray_tracing/scene/shading_parameter.cpp.i
.PHONY : projet/src/ray_tracing/scene/shading_parameter.i

# target to preprocess a source file
projet/src/ray_tracing/scene/shading_parameter.cpp.i:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/ray_tracing/scene/shading_parameter.cpp.i
.PHONY : projet/src/ray_tracing/scene/shading_parameter.cpp.i

projet/src/ray_tracing/scene/shading_parameter.s: projet/src/ray_tracing/scene/shading_parameter.cpp.s
.PHONY : projet/src/ray_tracing/scene/shading_parameter.s

# target to generate assembly for a file
projet/src/ray_tracing/scene/shading_parameter.cpp.s:
	$(MAKE) -f CMakeFiles/pgm.dir/build.make CMakeFiles/pgm.dir/projet/src/ray_tracing/scene/shading_parameter.cpp.s
.PHONY : projet/src/ray_tracing/scene/shading_parameter.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... pgm"
	@echo "... rebuild_cache"
	@echo "... projet/src/image/color.o"
	@echo "... projet/src/image/color.i"
	@echo "... projet/src/image/color.s"
	@echo "... projet/src/image/image.o"
	@echo "... projet/src/image/image.i"
	@echo "... projet/src/image/image.s"
	@echo "... projet/src/image/image_zbuffer.o"
	@echo "... projet/src/image/image_zbuffer.i"
	@echo "... projet/src/image/image_zbuffer.s"
	@echo "... projet/src/image/io/image_ppm.o"
	@echo "... projet/src/image/io/image_ppm.i"
	@echo "... projet/src/image/io/image_ppm.s"
	@echo "... projet/src/image/ivec2.o"
	@echo "... projet/src/image/ivec2.i"
	@echo "... projet/src/image/ivec2.s"
	@echo "... projet/src/image/texture.o"
	@echo "... projet/src/image/texture.i"
	@echo "... projet/src/image/texture.s"
	@echo "... projet/src/lib/3d/mat1x4.o"
	@echo "... projet/src/lib/3d/mat1x4.i"
	@echo "... projet/src/lib/3d/mat1x4.s"
	@echo "... projet/src/lib/3d/mat2.o"
	@echo "... projet/src/lib/3d/mat2.i"
	@echo "... projet/src/lib/3d/mat2.s"
	@echo "... projet/src/lib/3d/mat3.o"
	@echo "... projet/src/lib/3d/mat3.i"
	@echo "... projet/src/lib/3d/mat3.s"
	@echo "... projet/src/lib/3d/mat4.o"
	@echo "... projet/src/lib/3d/mat4.i"
	@echo "... projet/src/lib/3d/mat4.s"
	@echo "... projet/src/lib/3d/mat4x1.o"
	@echo "... projet/src/lib/3d/mat4x1.i"
	@echo "... projet/src/lib/3d/mat4x1.s"
	@echo "... projet/src/lib/3d/quaternion.o"
	@echo "... projet/src/lib/3d/quaternion.i"
	@echo "... projet/src/lib/3d/quaternion.s"
	@echo "... projet/src/lib/3d/vec2.o"
	@echo "... projet/src/lib/3d/vec2.i"
	@echo "... projet/src/lib/3d/vec2.s"
	@echo "... projet/src/lib/3d/vec3.o"
	@echo "... projet/src/lib/3d/vec3.i"
	@echo "... projet/src/lib/3d/vec3.s"
	@echo "... projet/src/lib/3d/vec4.o"
	@echo "... projet/src/lib/3d/vec4.i"
	@echo "... projet/src/lib/3d/vec4.s"
	@echo "... projet/src/lib/common/backtrace.o"
	@echo "... projet/src/lib/common/backtrace.i"
	@echo "... projet/src/lib/common/backtrace.s"
	@echo "... projet/src/lib/common/basic_functions.o"
	@echo "... projet/src/lib/common/basic_functions.i"
	@echo "... projet/src/lib/common/basic_functions.s"
	@echo "... projet/src/lib/common/exception_cpe.o"
	@echo "... projet/src/lib/common/exception_cpe.i"
	@echo "... projet/src/lib/common/exception_cpe.s"
	@echo "... projet/src/lib/mesh/format/mesh_io_obj.o"
	@echo "... projet/src/lib/mesh/format/mesh_io_obj.i"
	@echo "... projet/src/lib/mesh/format/mesh_io_obj.s"
	@echo "... projet/src/lib/mesh/format/mesh_io_off.o"
	@echo "... projet/src/lib/mesh/format/mesh_io_off.i"
	@echo "... projet/src/lib/mesh/format/mesh_io_off.s"
	@echo "... projet/src/lib/mesh/mesh.o"
	@echo "... projet/src/lib/mesh/mesh.i"
	@echo "... projet/src/lib/mesh/mesh.s"
	@echo "... projet/src/lib/mesh/mesh_basic.o"
	@echo "... projet/src/lib/mesh/mesh_basic.i"
	@echo "... projet/src/lib/mesh/mesh_basic.s"
	@echo "... projet/src/lib/mesh/mesh_io.o"
	@echo "... projet/src/lib/mesh/mesh_io.i"
	@echo "... projet/src/lib/mesh/mesh_io.s"
	@echo "... projet/src/lib/mesh/mesh_parametric.o"
	@echo "... projet/src/lib/mesh/mesh_parametric.i"
	@echo "... projet/src/lib/mesh/mesh_parametric.s"
	@echo "... projet/src/lib/mesh/triangle_index.o"
	@echo "... projet/src/lib/mesh/triangle_index.i"
	@echo "... projet/src/lib/mesh/triangle_index.s"
	@echo "... projet/src/local/main.o"
	@echo "... projet/src/local/main.i"
	@echo "... projet/src/local/main.s"
	@echo "... projet/src/ray_tracing/primitives/intersection_data.o"
	@echo "... projet/src/ray_tracing/primitives/intersection_data.i"
	@echo "... projet/src/ray_tracing/primitives/intersection_data.s"
	@echo "... projet/src/ray_tracing/primitives/plane.o"
	@echo "... projet/src/ray_tracing/primitives/plane.i"
	@echo "... projet/src/ray_tracing/primitives/plane.s"
	@echo "... projet/src/ray_tracing/primitives/primitive_basic.o"
	@echo "... projet/src/ray_tracing/primitives/primitive_basic.i"
	@echo "... projet/src/ray_tracing/primitives/primitive_basic.s"
	@echo "... projet/src/ray_tracing/primitives/sphere.o"
	@echo "... projet/src/ray_tracing/primitives/sphere.i"
	@echo "... projet/src/ray_tracing/primitives/sphere.s"
	@echo "... projet/src/ray_tracing/render_engine/render_engine.o"
	@echo "... projet/src/ray_tracing/render_engine/render_engine.i"
	@echo "... projet/src/ray_tracing/render_engine/render_engine.s"
	@echo "... projet/src/ray_tracing/scene/anti_aliasing_table.o"
	@echo "... projet/src/ray_tracing/scene/anti_aliasing_table.i"
	@echo "... projet/src/ray_tracing/scene/anti_aliasing_table.s"
	@echo "... projet/src/ray_tracing/scene/camera.o"
	@echo "... projet/src/ray_tracing/scene/camera.i"
	@echo "... projet/src/ray_tracing/scene/camera.s"
	@echo "... projet/src/ray_tracing/scene/light.o"
	@echo "... projet/src/ray_tracing/scene/light.i"
	@echo "... projet/src/ray_tracing/scene/light.s"
	@echo "... projet/src/ray_tracing/scene/material.o"
	@echo "... projet/src/ray_tracing/scene/material.i"
	@echo "... projet/src/ray_tracing/scene/material.s"
	@echo "... projet/src/ray_tracing/scene/ray.o"
	@echo "... projet/src/ray_tracing/scene/ray.i"
	@echo "... projet/src/ray_tracing/scene/ray.s"
	@echo "... projet/src/ray_tracing/scene/scene_parameter.o"
	@echo "... projet/src/ray_tracing/scene/scene_parameter.i"
	@echo "... projet/src/ray_tracing/scene/scene_parameter.s"
	@echo "... projet/src/ray_tracing/scene/shading_parameter.o"
	@echo "... projet/src/ray_tracing/scene/shading_parameter.i"
	@echo "... projet/src/ray_tracing/scene/shading_parameter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

